import type { NextPage } from 'next'
import Head from 'next/head'

import CatList from '../components/CatList'
import { HeaderLayout } from '../components/HeaderLayout'

const Home: NextPage = () => {
  return (
    <HeaderLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CatList />
    </HeaderLayout>
  )
}

export default Home
